# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(875, 470)
        self.label3_3 = QtWidgets.QLabel(Dialog)
        self.label3_3.setGeometry(QtCore.QRect(530, 80, 261, 16))
        self.label3_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 68, 97);")
        self.label3_3.setObjectName("label3_3")
        self.label4_4 = QtWidgets.QLabel(Dialog)
        self.label4_4.setGeometry(QtCore.QRect(470, 160, 47, 13))
        self.label4_4.setStyleSheet("font: 10pt \"Arial\";")
        self.label4_4.setObjectName("label4_4")
        self.label1_1 = QtWidgets.QLabel(Dialog)
        self.label1_1.setGeometry(QtCore.QRect(150, 120, 111, 111))
        self.label1_1.setStyleSheet("background-image: url(:/newPrefix/spark-drives.png);")
        self.label1_1.setText("")
        self.label1_1.setPixmap(QtGui.QPixmap(":/newPrefix/spark-drives.png"))
        self.label1_1.setScaledContents(True)
        self.label1_1.setObjectName("label1_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(580, 200, 231, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label5_5 = QtWidgets.QLabel(Dialog)
        self.label5_5.setGeometry(QtCore.QRect(470, 200, 91, 16))
        self.label5_5.setStyleSheet("font: 10pt \"Arial\";")
        self.label5_5.setObjectName("label5_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(410, -30, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1.setGeometry(QtCore.QRect(580, 160, 231, 21))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.label2_2 = QtWidgets.QLabel(Dialog)
        self.label2_2.setGeometry(QtCore.QRect(80, 270, 261, 21))
        self.label2_2.setStyleSheet("font: 12pt \"Arial\";\n"
"COLOR:rgb(255, 0, 0)")
        self.label2_2.setObjectName("label2_2")
        self.label5_7 = QtWidgets.QLabel(Dialog)
        self.label5_7.setGeometry(QtCore.QRect(470, 240, 101, 16))
        self.label5_7.setStyleSheet("font: 10pt \"Arial\";")
        self.label5_7.setObjectName("label5_7")
        self.label6_6 = QtWidgets.QLabel(Dialog)
        self.label6_6.setGeometry(QtCore.QRect(470, 280, 91, 16))
        self.label6_6.setStyleSheet("font: 10pt \"Arial\";")
        self.label6_6.setObjectName("label6_6")
        self.lineEdit2_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit2_3.setGeometry(QtCore.QRect(580, 240, 231, 21))
        self.lineEdit2_3.setObjectName("lineEdit2_3")
        self.lineEdit2_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit2_4.setGeometry(QtCore.QRect(580, 280, 231, 21))
        self.lineEdit2_4.setObjectName("lineEdit2_4")
        self.pushButton2_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton2_1.setGeometry(QtCore.QRect(610, 360, 75, 23))
        self.pushButton2_1.setObjectName("pushButton2_1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label3_3.setText(_translate("Dialog", "BOTTLE INSPECTION SYSTEM"))
        self.label4_4.setText(_translate("Dialog", "MAIL ID"))
        self.label5_5.setText(_translate("Dialog", "EMPLOYEE ID"))
        self.label2_2.setText(_translate("Dialog", "SPARK DRIVES AND AUTOMATION"))
        self.label5_7.setText(_translate("Dialog", "ORGANIZATION"))
        self.label6_6.setText(_translate("Dialog", "EMPLOYEE ID"))
        self.pushButton2_1.setText(_translate("Dialog", "SIGN UP"))
import pic


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
